import type { LocationSuggestion, PlaceOpeningHours, PlaceReviewSample } from "@/types/places";

import type { DemoBusiness, DemoCategoryKey, DemoWebsiteProfile } from "./types";

/**
 * Fictional businesses around Kadıköy, İstanbul for demo mode. Names, phone
 * numbers, review data and websites are invented; street names are real so the
 * map looks plausible. No real brands or people. Deterministic: no randomness.
 *
 * Gap profiles are deliberately varied: no website, unreachable website, weak
 * site, no phone, no hours, no photos, unanswered reviews, no Instagram, etc.
 */

export const DEMO_CENTER = { lat: 40.9903, lng: 29.029 } as const;
export const DEMO_WEBSITE_DOMAIN = "demo-sites.example";

const WEEKDAYS_TR = ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"] as const;
type Weekday = (typeof WEEKDAYS_TR)[number];

interface HoursSpec {
  open: string;
  close: string;
  closed?: Weekday[];
  /** Per-day overrides, e.g. shorter Saturday. */
  overrides?: Partial<Record<Weekday, string>>;
}

function hours(spec: HoursSpec): PlaceOpeningHours {
  const closed = new Set(spec.closed ?? []);
  const weekdayDescriptions = WEEKDAYS_TR.map((day) => {
    if (closed.has(day)) return `${day}: Kapalı`;
    const range = spec.overrides?.[day] ?? `${spec.open}–${spec.close}`;
    return `${day}: ${range}`;
  });
  return { weekdayDescriptions, periodsCount: WEEKDAYS_TR.length - closed.size };
}

function allDay(): PlaceOpeningHours {
  return { weekdayDescriptions: WEEKDAYS_TR.map((d) => `${d}: 24 saat açık`), periodsCount: 1 };
}

/** "216 336 41 18" -> national "(0216) 336 41 18", international "+90 216 336 41 18". */
function phone(local: string): { phoneNational: string; phoneInternational: string } {
  const [area, ...rest] = local.split(" ");
  return { phoneNational: `(0${area}) ${rest.join(" ")}`, phoneInternational: `+90 ${area} ${rest.join(" ")}` };
}

/** Review recency buckets; wording mirrors Google's Turkish relativePublishTimeDescription. */
const RECENCY = {
  w1: { relativeTime: "bir hafta önce", publishTime: "2026-09-10T14:20:00Z" },
  w2: { relativeTime: "2 hafta önce", publishTime: "2026-09-03T09:05:00Z" },
  w3: { relativeTime: "3 hafta önce", publishTime: "2026-08-27T18:40:00Z" },
  m1: { relativeTime: "bir ay önce", publishTime: "2026-08-14T11:15:00Z" },
  m2: { relativeTime: "2 ay önce", publishTime: "2026-07-16T20:30:00Z" },
  m3: { relativeTime: "3 ay önce", publishTime: "2026-06-12T08:50:00Z" },
  m5: { relativeTime: "5 ay önce", publishTime: "2026-04-09T16:00:00Z" },
  m8: { relativeTime: "8 ay önce", publishTime: "2026-01-21T13:25:00Z" },
  y1: { relativeTime: "bir yıl önce", publishTime: "2025-09-05T10:10:00Z" },
  y2: { relativeTime: "2 yıl önce", publishTime: "2024-08-19T15:45:00Z" },
} as const;
type Recency = keyof typeof RECENCY;

function rv(rating: number, when: Recency, hasOwnerReply: boolean | null): PlaceReviewSample {
  return { rating, ...RECENCY[when], hasOwnerReply };
}

interface Seed {
  slug: string;
  name: string;
  category: DemoCategoryKey;
  primaryType: string;
  types: string[];
  lat: number;
  lng: number;
  address: string;
  rating: number;
  ratingCount: number;
  phone?: string;
  hours?: PlaceOpeningHours | null;
  photos: number;
  reviews: PlaceReviewSample[];
  website?: { host: string; profile: DemoWebsiteProfile; scheme?: "http" | "https" };
  instagram?: string;
  priceLevel?: string;
  keywords?: string[];
}

function build(seed: Seed): DemoBusiness {
  const phones = seed.phone ? phone(seed.phone) : { phoneNational: null, phoneInternational: null };
  const websiteUri = seed.website ? `${seed.website.scheme ?? "https"}://${seed.website.host}.${DEMO_WEBSITE_DOMAIN}` : null;
  return {
    provider: "demo",
    providerPlaceId: `demo_${seed.slug}`,
    displayName: seed.name,
    formattedAddress: `${seed.address}, 34710 Kadıköy/İstanbul, Türkiye`,
    location: { lat: seed.lat, lng: seed.lng },
    primaryType: seed.primaryType,
    types: Array.from(new Set([seed.primaryType, ...seed.types, "point_of_interest", "establishment"])),
    businessStatus: "OPERATIONAL",
    city: "İstanbul",
    district: "Kadıköy",
    countryCode: "TR",
    rating: seed.rating,
    userRatingCount: seed.ratingCount,
    websiteUri,
    ...phones,
    // Real Google Maps URL pointing at the fictional coordinates; safe to open.
    googleMapsUri: `https://www.google.com/maps/search/?api=1&query=${seed.lat},${seed.lng}`,
    openingHours: seed.hours ?? null,
    photoCount: seed.photos,
    priceLevel: seed.priceLevel ?? null,
    reviewSample: seed.reviews,
    socialProfiles: seed.instagram ? [{ platform: "instagram", url: `https://www.instagram.com/${seed.instagram}` }] : null,
    categoryKey: seed.category,
    websiteProfile: seed.website?.profile ?? null,
    keywords: seed.keywords ?? [],
  };
}

const SEEDS: Seed[] = [
  // ---------------------------------------------------------------- restaurants_cafes (14)
  {
    slug: "lezzet-duragi",
    name: "Lezzet Durağı",
    category: "restaurants_cafes",
    primaryType: "turkish_restaurant",
    types: ["restaurant", "food"],
    lat: 40.9895,
    lng: 29.0272,
    address: "Söğütlüçeşme Cd. No:18, Osmanağa",
    rating: 4.6,
    ratingCount: 812,
    phone: "216 336 41 18",
    hours: hours({ open: "11:00", close: "23:00" }),
    photos: 10,
    reviews: [rv(5, "w1", true), rv(4, "w3", true), rv(5, "m1", true), rv(3, "m2", true), rv(5, "m5", false)],
    website: { host: "lezzetduragi", profile: "strong" },
    instagram: "lezzetduragi",
    priceLevel: "PRICE_LEVEL_MODERATE",
    keywords: ["ev yemekleri", "kebap", "restoran"],
  },
  {
    slug: "moda-kahve-evi",
    name: "Moda Kahve Evi",
    category: "restaurants_cafes",
    primaryType: "coffee_shop",
    types: ["cafe", "food"],
    lat: 40.9838,
    lng: 29.0261,
    address: "Moda Cd. No:64, Caferağa",
    rating: 4.4,
    ratingCount: 356,
    phone: "216 349 22 07",
    hours: hours({ open: "08:00", close: "23:30" }),
    photos: 7,
    reviews: [rv(5, "w2", false), rv(4, "m1", true), rv(4, "m3", false), rv(2, "m5", null)],
    website: { host: "modakahveevi", profile: "average" },
    instagram: "modakahveevi",
    priceLevel: "PRICE_LEVEL_MODERATE",
    keywords: ["kahve", "kafe", "üçüncü dalga"],
  },
  {
    slug: "bahariye-balikcisi",
    name: "Bahariye Balıkçısı",
    category: "restaurants_cafes",
    primaryType: "seafood_restaurant",
    types: ["restaurant", "food"],
    lat: 40.9878,
    lng: 29.0305,
    address: "Bahariye Cd. No:41, Caferağa",
    rating: 4.3,
    ratingCount: 540,
    phone: "216 347 80 15",
    hours: null,
    photos: 6,
    reviews: [rv(5, "w1", false), rv(4, "w3", false), rv(3, "m2", false), rv(5, "m8", false)],
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    keywords: ["balık", "meze", "restoran"],
  },
  {
    slug: "yeldegirmeni-firini",
    name: "Yeldeğirmeni Fırını",
    category: "restaurants_cafes",
    primaryType: "bakery",
    types: ["food", "store"],
    lat: 40.9948,
    lng: 29.0278,
    address: "Karakolhane Cd. No:9, Rasimpaşa",
    rating: 4.7,
    ratingCount: 233,
    phone: "216 414 63 90",
    hours: hours({ open: "07:00", close: "20:00", closed: ["Pazar"] }),
    photos: 3,
    reviews: [rv(5, "w2", null), rv(5, "m1", null), rv(4, "m3", false)],
    instagram: "yeldegirmenifirini",
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    keywords: ["fırın", "ekmek", "simit", "pastane"],
  },
  {
    slug: "rihtim-meyhanesi",
    name: "Rıhtım Meyhanesi",
    category: "restaurants_cafes",
    primaryType: "bar",
    types: ["restaurant", "food"],
    lat: 40.9909,
    lng: 29.0245,
    address: "Rıhtım Cd. No:27, Caferağa",
    rating: 4.1,
    ratingCount: 478,
    phone: "216 338 09 44",
    hours: hours({ open: "17:00", close: "01:00", closed: ["Pazartesi"] }),
    photos: 8,
    reviews: [rv(4, "w1", false), rv(2, "w3", false), rv(5, "m2", false), rv(4, "m5", false), rv(3, "y1", false)],
    website: { host: "rihtimmeyhanesi", profile: "unreachable" },
    priceLevel: "PRICE_LEVEL_MODERATE",
    keywords: ["meyhane", "rakı", "meze"],
  },
  {
    slug: "kalamis-brasserie",
    name: "Kalamış Brasserie",
    category: "restaurants_cafes",
    primaryType: "french_restaurant",
    types: ["restaurant", "cafe", "food"],
    lat: 40.9752,
    lng: 29.0378,
    address: "Fener Kalamış Cd. No:88, Fenerbahçe",
    rating: 4.5,
    ratingCount: 291,
    phone: "216 418 27 71",
    hours: hours({ open: "09:00", close: "00:00" }),
    photos: 9,
    reviews: [rv(5, "w2", true), rv(4, "m1", false), rv(5, "m3", true), rv(3, "m8", false)],
    website: { host: "kalamisbrasserie", profile: "menu_no_contact" },
    instagram: "kalamisbrasserie",
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    keywords: ["brasserie", "kahvaltı", "brunch"],
  },
  {
    slug: "goztepe-manti-evi",
    name: "Göztepe Mantı Evi",
    category: "restaurants_cafes",
    primaryType: "turkish_restaurant",
    types: ["restaurant", "food"],
    lat: 40.9781,
    lng: 29.0583,
    address: "Tütüncü Mehmet Efendi Cd. No:12, Göztepe",
    rating: 4.2,
    ratingCount: 167,
    phone: "216 355 14 62",
    hours: hours({ open: "11:30", close: "21:30", closed: ["Pazar"] }),
    photos: 4,
    reviews: [rv(5, "w3", false), rv(4, "m2", null), rv(3, "m5", false)],
    website: { host: "gozteptemantievi", profile: "menu_no_contact" },
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    keywords: ["mantı", "ev yemekleri"],
  },
  {
    slug: "fener-koftecisi",
    name: "Fener Köftecisi",
    category: "restaurants_cafes",
    primaryType: "restaurant",
    types: ["turkish_restaurant", "food"],
    lat: 40.9722,
    lng: 29.0412,
    address: "Fener Kalamış Cd. No:5, Fenerbahçe",
    rating: 4.0,
    ratingCount: 402,
    phone: "216 345 90 21",
    hours: null,
    photos: 2,
    reviews: [rv(4, "w2", false), rv(2, "m1", false), rv(5, "m3", false), rv(4, "y1", false)],
    website: { host: "fenerkoftecisi", profile: "weak_legacy", scheme: "http" },
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    keywords: ["köfte", "piyaz", "esnaf lokantası"],
  },
  {
    slug: "nohut-kafe",
    name: "Nohut Kafe",
    category: "restaurants_cafes",
    primaryType: "cafe",
    types: ["coffee_shop", "food"],
    lat: 40.9862,
    lng: 29.0335,
    address: "Bağdat Cd. No:21, Zühtüpaşa",
    rating: 3.9,
    ratingCount: 58,
    phone: "216 330 77 05",
    hours: hours({ open: "09:00", close: "22:00" }),
    photos: 5,
    reviews: [rv(4, "m1", null), rv(3, "m3", null), rv(5, "m8", null)],
    instagram: "nohutkafe",
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    keywords: ["kafe", "tatlı", "kahve"],
  },
  {
    slug: "acibadem-sofrasi",
    name: "Acıbadem Sofrası",
    category: "restaurants_cafes",
    primaryType: "restaurant",
    types: ["turkish_restaurant", "food"],
    lat: 41.0028,
    lng: 29.0442,
    address: "Acıbadem Cd. No:112, Acıbadem",
    rating: 4.1,
    ratingCount: 620,
    phone: "216 326 55 38",
    hours: null,
    photos: 6,
    reviews: [rv(5, "w1", false), rv(3, "w3", true), rv(4, "m2", false), rv(1, "m5", false), rv(5, "m8", false)],
    priceLevel: "PRICE_LEVEL_MODERATE",
    keywords: ["sulu yemek", "lokanta", "ev yemekleri"],
  },
  {
    slug: "hasanpasa-pide-salonu",
    name: "Hasanpaşa Pide Salonu",
    category: "restaurants_cafes",
    primaryType: "turkish_restaurant",
    types: ["restaurant", "food"],
    lat: 40.9975,
    lng: 29.0398,
    address: "Kurbağalıdere Cd. No:34, Hasanpaşa",
    rating: 4.4,
    ratingCount: 890,
    phone: "216 340 12 96",
    hours: null,
    photos: 1,
    reviews: [rv(5, "w1", false), rv(4, "w2", false), rv(5, "m1", false), rv(4, "m3", false), rv(2, "m5", false)],
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    keywords: ["pide", "lahmacun", "kebap"],
  },
  {
    slug: "kadife-pastanesi",
    name: "Kadife Pastanesi",
    category: "restaurants_cafes",
    primaryType: "bakery",
    types: ["cafe", "food", "store"],
    lat: 40.9902,
    lng: 29.0315,
    address: "Bahariye Cd. No:78, Caferağa",
    rating: 4.5,
    ratingCount: 310,
    hours: hours({ open: "08:30", close: "22:00" }),
    photos: 8,
    reviews: [rv(5, "w2", null), rv(4, "m1", null), rv(5, "m2", null), rv(4, "m8", null)],
    instagram: "kadifepastanesi",
    priceLevel: "PRICE_LEVEL_MODERATE",
    keywords: ["pastane", "pasta", "tatlı", "kafe"],
  },
  {
    slug: "sogutlucesme-kebap",
    name: "Söğütlüçeşme Kebap",
    category: "restaurants_cafes",
    primaryType: "restaurant",
    types: ["turkish_restaurant", "food"],
    lat: 40.9931,
    lng: 29.0348,
    address: "Söğütlüçeşme Cd. No:96, Osmanağa",
    rating: 3.4,
    ratingCount: 210,
    phone: "216 337 66 40",
    hours: null,
    photos: 0,
    reviews: [rv(2, "w1", false), rv(4, "m1", false), rv(3, "m3", false), rv(1, "m5", false)],
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    keywords: ["kebap", "dürüm"],
  },
  {
    slug: "moda-sahil-cay-bahcesi",
    name: "Moda Sahil Çay Bahçesi",
    category: "restaurants_cafes",
    primaryType: "cafe",
    types: ["food"],
    lat: 40.9793,
    lng: 29.0248,
    address: "Moda Sahil Yolu No:2, Caferağa",
    rating: 4.3,
    ratingCount: 740,
    hours: null,
    photos: 4,
    reviews: [rv(5, "w1", null), rv(4, "w3", null), rv(3, "m2", null), rv(5, "m8", null)],
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    keywords: ["çay bahçesi", "kafe", "sahil"],
  },

  // ---------------------------------------------------------------- hair_salons (6)
  {
    slug: "salon-ayna-kuafor",
    name: "Salon Ayna Kuaför",
    category: "hair_salons",
    primaryType: "hair_salon",
    types: ["beauty_salon", "health"],
    lat: 40.9884,
    lng: 29.0292,
    address: "Mühürdar Cd. No:33, Caferağa",
    rating: 4.8,
    ratingCount: 145,
    phone: "216 346 18 52",
    hours: hours({ open: "09:30", close: "20:00", closed: ["Pazar"] }),
    photos: 10,
    reviews: [rv(5, "w1", true), rv(5, "w3", true), rv(4, "m2", true), rv(5, "m5", true)],
    website: { host: "salonayna", profile: "booking_no_seo" },
    instagram: "salonaynakuafor",
    keywords: ["kuaför", "saç", "bayan kuaförü"],
  },
  {
    slug: "barber-muhurdar",
    name: "Barber Mühürdar",
    category: "hair_salons",
    primaryType: "barber_shop",
    types: ["hair_salon", "health"],
    lat: 40.9871,
    lng: 29.0284,
    address: "Mühürdar Cd. No:12, Caferağa",
    rating: 4.6,
    ratingCount: 88,
    phone: "216 348 03 19",
    hours: null,
    photos: 5,
    reviews: [rv(5, "w2", false), rv(4, "m1", false), rv(5, "m3", false)],
    instagram: "barbermuhurdar",
    keywords: ["berber", "erkek kuaförü", "sakal"],
  },
  {
    slug: "bahariye-erkek-kuaforu",
    name: "Bahariye Erkek Kuaförü",
    category: "hair_salons",
    primaryType: "barber_shop",
    types: ["hair_salon", "health"],
    lat: 40.9889,
    lng: 29.0322,
    address: "Bahariye Cd. No:55, Caferağa",
    rating: 4.2,
    ratingCount: 41,
    phone: "216 347 21 74",
    hours: null,
    photos: 0,
    reviews: [rv(5, "m1", null), rv(3, "m3", null), rv(4, "m8", null)],
    keywords: ["berber", "erkek kuaförü"],
  },
  {
    slug: "studio-sac-tasarim",
    name: "Studio Saç Tasarım",
    category: "hair_salons",
    primaryType: "hair_salon",
    types: ["beauty_salon", "health"],
    lat: 40.9812,
    lng: 29.0412,
    address: "Bağdat Cd. No:143, Kızıltoprak",
    rating: 4.5,
    ratingCount: 212,
    phone: "216 411 39 08",
    hours: hours({ open: "10:00", close: "20:30", closed: ["Pazar"] }),
    photos: 9,
    reviews: [rv(5, "w1", true), rv(4, "w3", false), rv(5, "m2", true), rv(2, "m5", false)],
    website: { host: "studiosac", profile: "template_generic" },
    instagram: "studiosactasarim",
    keywords: ["kuaför", "saç tasarım", "renklendirme"],
  },
  {
    slug: "makas-berber",
    name: "Makas Berber",
    category: "hair_salons",
    primaryType: "barber_shop",
    types: ["health"],
    lat: 40.9962,
    lng: 29.029,
    address: "Misak-ı Milli Sk. No:7, Rasimpaşa",
    rating: 4.9,
    ratingCount: 23,
    phone: "216 414 88 31",
    hours: hours({ open: "09:00", close: "21:00", closed: ["Pazar"] }),
    photos: 2,
    reviews: [rv(5, "w2", null), rv(5, "m1", null), rv(5, "m3", null)],
    keywords: ["berber", "tıraş"],
  },
  {
    slug: "elit-kuafor-goztepe",
    name: "Elit Kuaför Göztepe",
    category: "hair_salons",
    primaryType: "hair_salon",
    types: ["beauty_salon", "health"],
    lat: 40.9769,
    lng: 29.0552,
    address: "Fahrettin Kerim Gökay Cd. No:210, Göztepe",
    rating: 3.8,
    ratingCount: 67,
    phone: "216 359 47 26",
    hours: null,
    photos: 1,
    reviews: [rv(4, "m1", false), rv(2, "m3", false), rv(5, "m8", false), rv(3, "y1", false)],
    keywords: ["kuaför", "bayan kuaförü"],
  },

  // ---------------------------------------------------------------- dentists (4)
  {
    slug: "moda-agiz-ve-dis-sagligi",
    name: "Moda Ağız ve Diş Sağlığı Polikliniği",
    category: "dentists",
    primaryType: "dental_clinic",
    types: ["dentist", "doctor", "health"],
    lat: 40.9848,
    lng: 29.0298,
    address: "Moda Cd. No:110, Caferağa",
    rating: 4.9,
    ratingCount: 265,
    phone: "216 345 60 60",
    hours: hours({ open: "09:00", close: "19:00", closed: ["Pazar"], overrides: { Cumartesi: "09:00–15:00" } }),
    photos: 8,
    reviews: [rv(5, "w1", true), rv(5, "w2", true), rv(5, "m1", true), rv(4, "m3", true), rv(5, "m8", true)],
    website: { host: "modadis", profile: "strong" },
    instagram: "modadisklinigi",
    keywords: ["diş hekimi", "implant", "ortodonti", "diş kliniği"],
  },
  {
    slug: "bagdat-dis-klinigi",
    name: "Bağdat Diş Kliniği",
    category: "dentists",
    primaryType: "dental_clinic",
    types: ["dentist", "health"],
    lat: 40.9794,
    lng: 29.0466,
    address: "Bağdat Cd. No:201, Feneryolu",
    rating: 4.6,
    ratingCount: 132,
    phone: "216 369 42 15",
    hours: hours({ open: "09:30", close: "18:30", closed: ["Pazar"] }),
    photos: 6,
    reviews: [rv(5, "w3", true), rv(4, "m2", false), rv(5, "m5", true), rv(3, "y1", false)],
    website: { host: "bagdatdis", profile: "booking_no_seo" },
    keywords: ["diş hekimi", "diş beyazlatma", "diş kliniği"],
  },
  {
    slug: "feneryolu-dis-hekimligi",
    name: "Feneryolu Diş Hekimliği",
    category: "dentists",
    primaryType: "dentist",
    types: ["health"],
    lat: 40.9788,
    lng: 29.0492,
    address: "Fahrettin Kerim Gökay Cd. No:64, Feneryolu",
    rating: 4.3,
    ratingCount: 39,
    phone: "216 347 55 02",
    hours: null,
    photos: 1,
    reviews: [rv(5, "m1", null), rv(4, "m3", false), rv(3, "m8", null)],
    keywords: ["diş hekimi", "dolgu"],
  },
  {
    slug: "yeldegirmeni-dis-poliklinigi",
    name: "Yeldeğirmeni Diş Polikliniği",
    category: "dentists",
    primaryType: "dentist",
    types: ["dental_clinic", "health"],
    lat: 40.9955,
    lng: 29.0262,
    address: "Duatepe Sk. No:14, Rasimpaşa",
    rating: 4.0,
    ratingCount: 18,
    phone: "216 418 90 33",
    hours: null,
    photos: 0,
    reviews: [rv(4, "m2", null), rv(5, "m5", null), rv(3, "y1", null)],
    keywords: ["diş hekimi", "diş polikliniği"],
  },

  // ---------------------------------------------------------------- gyms_pilates (4)
  {
    slug: "rihtim-fitness",
    name: "Rıhtım Fitness",
    category: "gyms_pilates",
    primaryType: "gym",
    types: ["fitness_center", "health"],
    lat: 40.9916,
    lng: 29.0238,
    address: "Rıhtım Cd. No:60, Caferağa",
    rating: 4.4,
    ratingCount: 388,
    phone: "216 338 71 80",
    hours: hours({ open: "06:30", close: "23:00", overrides: { Pazar: "09:00–20:00" } }),
    photos: 10,
    reviews: [rv(5, "w1", false), rv(3, "w3", true), rv(4, "m2", false), rv(2, "m5", true), rv(5, "m8", false)],
    instagram: "rihtimfitness",
    keywords: ["spor salonu", "fitness", "gym"],
  },
  {
    slug: "moda-pilates-studyosu",
    name: "Moda Pilates Stüdyosu",
    category: "gyms_pilates",
    primaryType: "fitness_center",
    types: ["yoga_studio", "health"],
    lat: 40.9832,
    lng: 29.0279,
    address: "Ferit Tek Sk. No:21, Caferağa",
    rating: 4.9,
    ratingCount: 97,
    phone: "216 349 04 46",
    hours: hours({ open: "07:00", close: "21:00", closed: ["Pazar"] }),
    photos: 7,
    reviews: [rv(5, "w1", true), rv(5, "w2", true), rv(5, "m1", true), rv(4, "m3", true)],
    website: { host: "modapilates", profile: "booking_no_seo" },
    instagram: "modapilates",
    keywords: ["pilates stüdyosu", "reformer pilates", "pilates"],
  },
  {
    slug: "goztepe-spor-merkezi",
    name: "Göztepe Spor Merkezi",
    category: "gyms_pilates",
    primaryType: "gym",
    types: ["fitness_center", "health"],
    lat: 40.9803,
    lng: 29.0602,
    address: "Bağdat Cd. No:288, Göztepe",
    rating: 4.1,
    ratingCount: 254,
    phone: "216 302 66 12",
    hours: hours({ open: "07:00", close: "22:30" }),
    photos: 5,
    reviews: [rv(4, "w2", false), rv(3, "m1", false), rv(5, "m3", false), rv(2, "m8", false)],
    website: { host: "gozteptespor", profile: "average" },
    keywords: ["spor salonu", "fitness", "yüzme"],
  },
  {
    slug: "yoga-yeldegirmeni",
    name: "Yoga Yeldeğirmeni",
    category: "gyms_pilates",
    primaryType: "yoga_studio",
    types: ["fitness_center", "health"],
    lat: 40.9941,
    lng: 29.0301,
    address: "Karakolhane Cd. No:44, Rasimpaşa",
    rating: 4.7,
    ratingCount: 52,
    hours: hours({ open: "08:00", close: "21:00", closed: ["Pazartesi"] }),
    photos: 6,
    reviews: [rv(5, "w3", null), rv(5, "m2", null), rv(4, "m5", null)],
    instagram: "yogayeldegirmeni",
    keywords: ["yoga", "pilates stüdyosu", "meditasyon"],
  },

  // ---------------------------------------------------------------- real_estate (4)
  {
    slug: "bagdat-emlak-ofisi",
    name: "Bağdat Emlak Ofisi",
    category: "real_estate",
    primaryType: "real_estate_agency",
    types: ["finance"],
    lat: 40.9821,
    lng: 29.0431,
    address: "Bağdat Cd. No:167, Kızıltoprak",
    rating: 4.2,
    ratingCount: 76,
    phone: "216 345 32 90",
    hours: null,
    photos: 3,
    reviews: [rv(5, "w2", false), rv(4, "m1", false), rv(2, "m3", false), rv(5, "m8", false)],
    website: { host: "bagdatemlak", profile: "average" },
    keywords: ["emlak", "kiralık daire", "satılık"],
  },
  {
    slug: "kalamis-gayrimenkul",
    name: "Kalamış Gayrimenkul",
    category: "real_estate",
    primaryType: "real_estate_agency",
    types: ["finance"],
    lat: 40.9766,
    lng: 29.0355,
    address: "Kalamış Cd. No:15, Fenerbahçe",
    rating: 4.5,
    ratingCount: 44,
    phone: "216 418 50 27",
    hours: hours({ open: "09:00", close: "19:00", closed: ["Pazar"] }),
    photos: 4,
    reviews: [rv(5, "w1", true), rv(4, "m2", false), rv(5, "m5", true)],
    website: { host: "kalamisgayrimenkul", profile: "corporate" },
    instagram: "kalamisgayrimenkul",
    keywords: ["gayrimenkul", "emlak", "yatırım"],
  },
  {
    slug: "fikirtepe-konut-danismanlik",
    name: "Fikirtepe Konut Danışmanlık",
    category: "real_estate",
    primaryType: "real_estate_agency",
    types: ["finance"],
    lat: 40.9982,
    lng: 29.0518,
    address: "Mandıra Cd. No:80, Fikirtepe",
    rating: 3.3,
    ratingCount: 31,
    phone: "216 545 18 63",
    hours: null,
    photos: 0,
    reviews: [rv(1, "w3", false), rv(4, "m2", false), rv(2, "m5", false), rv(5, "y1", false)],
    keywords: ["emlak", "konut", "kentsel dönüşüm"],
  },
  {
    slug: "acibadem-emlak",
    name: "Acıbadem Emlak",
    category: "real_estate",
    primaryType: "real_estate_agency",
    types: ["finance"],
    lat: 41.0041,
    lng: 29.0463,
    address: "Çeçen Sk. No:9, Acıbadem",
    rating: 4.0,
    ratingCount: 22,
    phone: "216 326 14 09",
    hours: null,
    photos: 2,
    reviews: [rv(5, "m1", null), rv(3, "m3", null), rv(4, "m8", null)],
    website: { host: "acibadememlak", profile: "unreachable" },
    keywords: ["emlak", "kiralık", "satılık"],
  },

  // ---------------------------------------------------------------- accounting_tax (3)
  {
    slug: "kadikoy-mali-musavirlik",
    name: "Kadıköy Mali Müşavirlik",
    category: "accounting_tax",
    primaryType: "accounting",
    types: ["finance"],
    lat: 40.991,
    lng: 29.0332,
    address: "Halitağa Cd. No:22 Kat:3, Osmanağa",
    rating: 4.6,
    ratingCount: 38,
    phone: "216 336 74 45",
    hours: hours({ open: "09:00", close: "18:00", closed: ["Cumartesi", "Pazar"] }),
    photos: 1,
    reviews: [rv(5, "m1", true), rv(5, "m3", true), rv(4, "m8", true)],
    website: { host: "kadikoymalimusavirlik", profile: "corporate" },
    keywords: ["mali müşavir", "smmm", "muhasebe", "vergi"],
  },
  {
    slug: "denge-muhasebe",
    name: "Denge Muhasebe",
    category: "accounting_tax",
    primaryType: "accounting",
    types: ["finance"],
    lat: 40.9998,
    lng: 29.0415,
    address: "Uzunçayır Cd. No:5 Kat:2, Hasanpaşa",
    rating: 4.3,
    ratingCount: 19,
    phone: "216 340 29 81",
    hours: hours({ open: "08:30", close: "18:00", closed: ["Cumartesi", "Pazar"] }),
    photos: 0,
    reviews: [rv(4, "m2", null), rv(5, "m5", null), rv(4, "y1", null)],
    website: { host: "dengemuhasebe", profile: "corporate" },
    keywords: ["mali müşavir", "muhasebe", "bordro"],
  },
  {
    slug: "hasanpasa-smmm-burosu",
    name: "Hasanpaşa SMMM Bürosu",
    category: "accounting_tax",
    primaryType: "accounting",
    types: ["finance"],
    lat: 40.9968,
    lng: 29.0372,
    address: "Kurbağalıdere Cd. No:70 Kat:1, Hasanpaşa",
    rating: 4.1,
    ratingCount: 6,
    phone: "216 339 08 57",
    hours: null,
    photos: 0,
    reviews: [rv(5, "m3", null), rv(3, "m8", null), rv(4, "y2", null)],
    keywords: ["mali müşavir", "smmm", "muhasebe"],
  },

  // ---------------------------------------------------------------- education_courses (3)
  {
    slug: "moda-dil-kursu",
    name: "Moda Dil Kursu",
    category: "education_courses",
    primaryType: "language_school",
    types: ["school", "education"],
    lat: 40.9856,
    lng: 29.0306,
    address: "Moda Cd. No:88, Caferağa",
    rating: 4.7,
    ratingCount: 143,
    phone: "216 346 90 12",
    hours: hours({ open: "09:00", close: "21:00", overrides: { Cumartesi: "10:00–18:00", Pazar: "10:00–16:00" } }),
    photos: 6,
    reviews: [rv(5, "w1", true), rv(5, "w3", false), rv(4, "m2", true), rv(3, "m8", false)],
    website: { host: "modadilkursu", profile: "average" },
    instagram: "modadilkursu",
    keywords: ["dil kursu", "ingilizce", "kurs merkezi", "almanca"],
  },
  {
    slug: "goztepe-matematik-atolyesi",
    name: "Göztepe Matematik Atölyesi",
    category: "education_courses",
    primaryType: "school",
    types: ["education"],
    lat: 40.9775,
    lng: 29.0561,
    address: "Tütüncü Mehmet Efendi Cd. No:58, Göztepe",
    rating: 4.9,
    ratingCount: 61,
    phone: "216 355 71 33",
    hours: hours({ open: "13:00", close: "21:00", closed: ["Pazar"], overrides: { Cumartesi: "09:00–18:00" } }),
    photos: 3,
    reviews: [rv(5, "w2", null), rv(5, "m1", null), rv(5, "m5", null)],
    instagram: "gozteptematematik",
    keywords: ["kurs merkezi", "matematik", "etüt", "özel ders"],
  },
  {
    slug: "kadikoy-muzik-okulu",
    name: "Kadıköy Müzik Okulu",
    category: "education_courses",
    primaryType: "school",
    types: ["education"],
    lat: 40.9923,
    lng: 29.0262,
    address: "Rıhtım Cd. No:81, Rasimpaşa",
    rating: 4.5,
    ratingCount: 84,
    hours: hours({ open: "11:00", close: "21:00", closed: ["Pazartesi"] }),
    photos: 5,
    reviews: [rv(5, "w3", false), rv(4, "m2", false), rv(5, "m5", false), rv(3, "y1", false)],
    instagram: "kadikoymuzikokulu",
    keywords: ["kurs merkezi", "müzik kursu", "gitar", "piyano"],
  },

  // ---------------------------------------------------------------- hotels (3)
  {
    slug: "rihtim-butik-otel",
    name: "Rıhtım Butik Otel",
    category: "hotels",
    primaryType: "hotel",
    types: ["lodging"],
    lat: 40.9927,
    lng: 29.0233,
    address: "Rıhtım Cd. No:3, Caferağa",
    rating: 4.6,
    ratingCount: 512,
    phone: "216 336 00 90",
    hours: allDay(),
    photos: 10,
    reviews: [rv(5, "w1", true), rv(4, "w2", true), rv(5, "m1", true), rv(3, "m3", true), rv(5, "m8", true)],
    website: { host: "rihtimbutikotel", profile: "strong" },
    instagram: "rihtimbutikotel",
    priceLevel: "PRICE_LEVEL_MODERATE",
    keywords: ["otel", "butik otel", "konaklama"],
  },
  {
    slug: "moda-pansiyon",
    name: "Moda Pansiyon",
    category: "hotels",
    primaryType: "guest_house",
    types: ["lodging"],
    lat: 40.9828,
    lng: 29.0251,
    address: "Cem Sk. No:6, Caferağa",
    rating: 4.2,
    ratingCount: 96,
    phone: "216 349 61 27",
    hours: allDay(),
    photos: 4,
    reviews: [rv(4, "w3", false), rv(5, "m2", false), rv(3, "m5", false), rv(4, "y1", false)],
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    keywords: ["pansiyon", "konaklama", "hostel"],
  },
  {
    slug: "fenerbahce-suit-otel",
    name: "Fenerbahçe Suit Otel",
    category: "hotels",
    primaryType: "hotel",
    types: ["lodging"],
    lat: 40.9741,
    lng: 29.0398,
    address: "Fener Kalamış Cd. No:120, Fenerbahçe",
    rating: 3.9,
    ratingCount: 204,
    phone: "216 414 25 70",
    hours: allDay(),
    photos: 3,
    reviews: [rv(4, "w2", false), rv(2, "m1", null), rv(5, "m3", false), rv(3, "m8", null)],
    website: { host: "fenerbahcesuit", profile: "under_construction" },
    priceLevel: "PRICE_LEVEL_MODERATE",
    keywords: ["otel", "suit", "konaklama"],
  },

  // ---------------------------------------------------------------- auto_services (3)
  {
    slug: "fikirtepe-oto-servis",
    name: "Fikirtepe Oto Servis",
    category: "auto_services",
    primaryType: "car_repair",
    types: ["store"],
    lat: 40.9995,
    lng: 29.0498,
    address: "Mandıra Cd. No:41, Dumlupınar",
    rating: 4.5,
    ratingCount: 128,
    phone: "216 545 33 08",
    hours: hours({ open: "08:30", close: "19:00", closed: ["Pazar"] }),
    photos: 6,
    reviews: [rv(5, "w1", true), rv(4, "m1", false), rv(5, "m3", true), rv(3, "m8", false)],
    website: { host: "fikirtepeotoservis", profile: "average" },
    keywords: ["oto servis", "tamir", "periyodik bakım"],
  },
  {
    slug: "hasanpasa-oto-yikama",
    name: "Hasanpaşa Oto Yıkama",
    category: "auto_services",
    primaryType: "car_wash",
    types: ["store"],
    lat: 40.9989,
    lng: 29.0378,
    address: "Uzunçayır Cd. No:26, Hasanpaşa",
    rating: 4.3,
    ratingCount: 75,
    phone: "216 340 84 16",
    hours: hours({ open: "08:00", close: "20:00" }),
    photos: 2,
    reviews: [rv(5, "w2", false), rv(4, "m2", false), rv(3, "m5", false)],
    website: { host: "hasanpasaotoyikama", profile: "weak_legacy", scheme: "http" },
    keywords: ["oto yıkama", "detaylı temizlik", "pasta cila"],
  },
  {
    slug: "kosuyolu-otomotiv-galeri",
    name: "Koşuyolu Otomotiv Galeri",
    category: "auto_services",
    primaryType: "car_dealer",
    types: ["store"],
    lat: 41.0052,
    lng: 29.0301,
    address: "Koşuyolu Cd. No:55, Koşuyolu",
    rating: 4.0,
    ratingCount: 47,
    phone: "216 326 90 44",
    hours: null,
    photos: 8,
    reviews: [rv(5, "m1", null), rv(2, "m3", null), rv(4, "m8", null), rv(5, "y1", null)],
    instagram: "kosuyoluotomotiv",
    keywords: ["oto galeri", "ikinci el araç", "araba"],
  },

  // ---------------------------------------------------------------- beauty (2)
  {
    slug: "nail-art-moda",
    name: "Nail Art Moda",
    category: "beauty",
    primaryType: "nail_salon",
    types: ["beauty_salon", "health"],
    lat: 40.9866,
    lng: 29.0272,
    address: "Şair Nefi Sk. No:10, Caferağa",
    rating: 4.8,
    ratingCount: 119,
    phone: "216 349 77 54",
    hours: hours({ open: "10:00", close: "20:00", closed: ["Pazar"] }),
    photos: 9,
    reviews: [rv(5, "w1", true), rv(5, "w3", true), rv(4, "m2", true), rv(5, "m5", true)],
    website: { host: "nailartmoda", profile: "template_generic" },
    instagram: "nailartmoda",
    keywords: ["manikür", "protez tırnak", "güzellik"],
  },
  {
    slug: "kalamis-spa-guzellik",
    name: "Kalamış Spa & Güzellik",
    category: "beauty",
    primaryType: "spa",
    types: ["beauty_salon", "skin_care_clinic", "health"],
    lat: 40.9758,
    lng: 29.0364,
    address: "Fener Kalamış Cd. No:60, Fenerbahçe",
    rating: 4.7,
    ratingCount: 233,
    phone: "216 418 66 00",
    hours: hours({ open: "10:00", close: "21:00" }),
    photos: 10,
    reviews: [rv(5, "w1", true), rv(4, "w2", false), rv(5, "m1", true), rv(5, "m3", true), rv(3, "m8", false)],
    website: { host: "kalamisspa", profile: "strong" },
    instagram: "kalamisspa",
    keywords: ["spa", "cilt bakımı", "masaj", "güzellik merkezi"],
  },

  // ---------------------------------------------------------------- retail (2)
  {
    slug: "bahariye-ayakkabi",
    name: "Bahariye Ayakkabı",
    category: "retail",
    primaryType: "shoe_store",
    types: ["clothing_store", "store"],
    lat: 40.9893,
    lng: 29.0313,
    address: "Bahariye Cd. No:62, Caferağa",
    rating: 4.1,
    ratingCount: 66,
    phone: "216 347 11 90",
    hours: null,
    photos: 3,
    reviews: [rv(4, "w3", false), rv(5, "m2", false), rv(2, "m5", false), rv(4, "y1", false)],
    keywords: ["ayakkabı", "mağaza", "çanta"],
  },
  {
    slug: "moda-hediyelik-dukkani",
    name: "Moda Hediyelik Dükkanı",
    category: "retail",
    primaryType: "gift_shop",
    types: ["store"],
    lat: 40.9846,
    lng: 29.0268,
    address: "Moda Cd. No:71, Caferağa",
    rating: 4.6,
    ratingCount: 52,
    hours: hours({ open: "11:00", close: "20:00" }),
    photos: 7,
    reviews: [rv(5, "w2", null), rv(5, "m1", null), rv(4, "m3", null)],
    instagram: "modahediyelik",
    keywords: ["hediyelik", "tasarım", "mağaza"],
  },
];

export const DEMO_BUSINESSES: readonly DemoBusiness[] = SEEDS.map(build);

export function findDemoBusiness(providerPlaceId: string): DemoBusiness | undefined {
  return DEMO_BUSINESSES.find((b) => b.providerPlaceId === providerPlaceId);
}

/** Wizard "search a place" suggestions for demo mode. */
export const DEMO_LOCATIONS: readonly LocationSuggestion[] = [
  {
    label: "Kadıköy, İstanbul, Türkiye",
    location: { lat: 40.9903, lng: 29.029 },
    viewport: { north: 41.01, south: 40.965, east: 29.075, west: 29.0 },
    providerPlaceId: "demo_loc_kadikoy",
  },
  {
    label: "Beşiktaş, İstanbul, Türkiye",
    location: { lat: 41.043, lng: 29.0094 },
    viewport: { north: 41.11, south: 41.03, east: 29.05, west: 28.98 },
    providerPlaceId: "demo_loc_besiktas",
  },
  {
    label: "Şişli, İstanbul, Türkiye",
    location: { lat: 41.0602, lng: 28.9877 },
    viewport: { north: 41.09, south: 41.04, east: 29.02, west: 28.96 },
    providerPlaceId: "demo_loc_sisli",
  },
  {
    label: "Üsküdar, İstanbul, Türkiye",
    location: { lat: 41.0234, lng: 29.0152 },
    viewport: { north: 41.06, south: 41.0, east: 29.09, west: 29.0 },
    providerPlaceId: "demo_loc_uskudar",
  },
  {
    label: "Bakırköy, İstanbul, Türkiye",
    location: { lat: 40.9819, lng: 28.8772 },
    viewport: { north: 41.0, south: 40.955, east: 28.9, west: 28.83 },
    providerPlaceId: "demo_loc_bakirkoy",
  },
];
